project:
  type: website
  output-dir: docs
  resources:
    - files/cv.pdf
    - posts/soundscape/output_trimmed.mp3

website:
  title: "tom savage"
  favicon: favicon.ico
  site-url: https://sav.phd
  description: "the lot"
  navbar:
    collapse: false
    # left:
      # - text: "Home"
      #   file: index.qmd
      # - text: "Portfolio"
      #   file: portfolio.qmd
      # - text: "About Me"
      #   file: about.qmd
    search: true
format:
  html:
    theme:
      - Simplex
      - custom.scss
    backgroundcolor: "white"
    fontcolor: "#000000"
    linestretch: 1.3
    grid:
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 20px
      # body-width: 600px

    css: styles.css



