project:
  type: website
  output-dir: docs

website:
  title: "TRS"
  favicon: favicon.ico
  #title: "TRS"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/trsav
      - icon: twitter
        href: https://twitter.com/savage_tom
format:
  html:
    theme:
    - Simplex
    - custom.scss
    backgroundcolor: "#ffffff"
    fontcolor: "#000000"
    linestretch: 1.3

    css: styles.css



