project:
  type: website
  output-dir: docs
  resources:
    - posts/soundscape/output_trimmed.mp3

website:
  title: "trsav"
  favicon: favicon.ico
  site-url: https://sav.phd
  description: ""
  navbar:
    collapse: false
    search: true
format:
  html:
    theme:
      - Simplex
      - custom.scss
    backgroundcolor: "white"
    fontcolor: "#000000"
    linestretch: 1.3
    grid:
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 20px
      # body-width: 600px

    css: styles.css



