project:
  type: website
  output-dir: docs

website:
  title: "tom savage"
  favicon: favicon.ico
  navbar:
    collapse: false
    left:
      # - text: "Home"
      #   file: index.qmd
      - text: "portfolio"
        file: portfolio.qmd
      - text: "about me"
        file: about.qmd
    search: true
    site-url: https://sav.phd
    description: "Tom Savage's Blog"
format:
  html:
    theme:
      - Simplex
      - custom.scss
    backgroundcolor: "white"
    fontcolor: "#000000"
    linestretch: 1.3
    grid:
      sidebar-width: 300px
      margin-width: 300px
      gutter-width: 20px
      # body-width: 600px

    css: styles.css



